name = "Lemonlight"
author = "robotkoer"
version = "10.1.0-alpha.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "08b83dd8dff503157c957adcfae2b661d960e2da225072c0b452f29fa6464050"

[versions]
fabric = "0.16.14"
minecraft = "1.21.7"
