name = "Lemonlight"
author = "robotkoer"
version = "13.1.0-alpha.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "12b9671be1e0e1fcfcf51acb0d2734618dc1bbf07d697a6537d4e1d8231e3e9c"

[versions]
fabric = "0.18.6"
minecraft = "26.1.1"
