name = "Lemonlight Full"
author = "robotkoer"
version = "12.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9d45b479e0d6eaec11e29883f4d497e074ace5080f568643a30bce8aced365ef"

[versions]
fabric = "0.19.3"
minecraft = "1.21.11"
