name = "Lemonlight"
author = "robotkoer"
version = "5.0.0-alpha.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "75da4737943239775301a491a04542ca6bdb3640a667b8be1a84125102a63efe"

[versions]
fabric = "0.14.21"
minecraft = "1.20"
