name = "Lemonlight"
author = "robotkoer"
version = "14.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fbc2e120a90e9e1443fd73e445a3266cce85a4ab5b767c4957e41ca4d14d55ee"

[versions]
fabric = "0.19.5"
minecraft = "26.2"
