name = "Lemonlight"
author = "robotkoer"
version = "14.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5ece7533bc941b509d07e7f31e889f1e5b04f453a7fb1b9a8870c07d8540405d"

[versions]
fabric = "0.19.5"
minecraft = "26.2"
