name = "Lemonlight Full"
author = "robotkoer"
version = "11.0.0-alpha.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c7780669a9dbd163d3cac07e0456f544378d9d1759488ddf27af430e2e9fc3de"

[versions]
fabric = "0.17.2"
minecraft = "1.21.9"
