name = "Lemonlight"
author = "robotkoer"
version = "15.0.0-alpha.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "806be7c4506b99b7a5da851c5f0f8ad96b676009ee8b22254dd4b72b95a57e37"

[versions]
fabric = "0.19.5"
minecraft = "26.3"
