name = "Lemonlight"
author = "robotkoer"
version = "15.0.0-alpha.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e73c0a52a0c34df816b6fee6a2b2f215c3a458e9c24109a668c7b3117bf262c9"

[versions]
fabric = "0.19.5"
minecraft = "26.3"
