name = "Lemonlight"
author = "robotkoer"
version = "15.0.0-alpha.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c969dc5cd240e45eb0c06b20cb58c5a51cd05b83ad5d5baec7a28de3fc4fb82a"

[versions]
fabric = "0.19.5"
minecraft = "26.3"
