name = "Lemonlight"
author = "robotkoer"
version = "5.6.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "24826dffe2729b05d0521b81f90a2fae858f092777877a49be8abf251f8adb7b"

[versions]
fabric = "0.15.7"
minecraft = "1.20.2"
