name = "Lemonlight"
author = "robotkoer"
version = "9.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "43de89f155fed4b3bf03e40c722b1219f9f2c4d667e992a5455256c5981ddbe5"

[versions]
fabric = "0.19.3"
minecraft = "1.21.5"
