name = "Lemonlight"
author = "robotkoer"
version = "13.0.0-alpha.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "544e71831542295d8e1b23f23d0ae8c3cec1fa702c6c44d34c2dd868c5542610"

[versions]
fabric = "0.18.5"
minecraft = "26.1"
