name = "Lemonlight"
author = "robotkoer"
version = "6.4.0-beta.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6b621a16ecc703766f8a24a4933904afde7f1567664378232b15c969a768acaa"

[versions]
fabric = "0.16.10"
minecraft = "1.21.3"
