name = "Lemonlight"
author = "robotkoer"
version = "5.7.0-alpha.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4f3115ccb27aef787e849cac9597205c3a4b7fea4a694beb630dcf9f96780fd5"

[versions]
fabric = "0.15.0"
minecraft = "1.20.3"
