name = "Lemonlight"
author = "robotkoer"
version = "4.5.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c3df6e9f7852de561f0e21cc53040b04cc8ba66c355a6fba638b556a8e006065"

[versions]
fabric = "0.14.19"
minecraft = "1.19.2"
