name = "Lemonlight Full"
author = "robotkoer"
version = "11.3.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "12ced25bee3dcf95d24b7786f9fae0e569dee3b75a5a8e2e497b805525a78bb5"

[versions]
fabric = "0.19.3"
minecraft = "1.21.10"
