name = "Lemonlight"
author = "robotkoer"
version = "6.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d9eb8e086210ccf628c70fceefc3eeaf5fd88c8e607e6cc50ea96922a62a6efa"

[versions]
fabric = "0.19.3"
minecraft = "1.21.1"
