name = "Lemonlight"
author = "robotkoer"
version = "10.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7878b21c99f2572090a5ba01e4fb45f683dd84277baab42370bd7f2287770432"

[versions]
fabric = "0.19.3"
minecraft = "1.21.8"
