name = "Lemonlight"
author = "robotkoer"
version = "10.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f5dab422d153a7611de710d3d4bebb28ed962f227b032370425f36c1f5730369"

[versions]
fabric = "0.19.3"
minecraft = "1.21.8"
