name = "Lemonlight"
author = "robotkoer"
version = "12.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "450ecedfcdc19d50e19f514f58dfb7e2403a4c6cfbd5efec714f9017547961a5"

[versions]
fabric = "0.19.3"
minecraft = "1.21.11"
