name = "Lemonlight"
author = "robotkoer"
version = "12.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eebbcd2ac5b26de1375f53ef93d1d70c7c45e11b101d1040b18742772e314baa"

[versions]
fabric = "0.19.3"
minecraft = "1.21.11"
