name = "Lemonlight"
author = "robotkoer"
version = "6.3.0-alpha.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f20ea28af0d763eefb3859988eb90f47150d4e35d91bd8d15692c426d9cdfd14"

[versions]
fabric = "0.16.7"
minecraft = "1.21.2"
