name = "Lemonlight"
author = "robotkoer"
version = "5.4.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f96f2d544d74a618d661181a7cc09dd6419fe55626ac12a47f9d4827aec4324f"

[versions]
fabric = "0.14.23"
minecraft = "1.20.1"
