name = "Lemonlight"
author = "robotkoer"
version = "11.0.0-alpha.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6a2cf24e8dde474df3a60b868cef86937d45d8ab7a1dee8ea7d8d40270e5f465"

[versions]
fabric = "0.17.2"
minecraft = "1.21.9"
