name = "Lemonlight"
author = "robotkoer"
version = "11.0.0-alpha.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9164f3e85ce92cfd16155f88a28c036758fa31e3dc5e1d3ccb185022dd54e526"

[versions]
fabric = "0.17.2"
minecraft = "1.21.9"
