name = "Lemonlight"
author = "robotkoer"
version = "5.13.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bdef8f09d33cf7b59c04b5b7846fa6f5bf1a3f299df2a9a14dc31e342ecdd0ff"

[versions]
fabric = "0.19.3"
minecraft = "1.20.6"
