name = "Lemonlight"
author = "robotkoer"
version = "11.3.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0f1f140c73f7c728f53d9233cfaacb438330b01dff09c3ae46aa0a00cf4b28b5"

[versions]
fabric = "0.19.3"
minecraft = "1.21.10"
