name = "Lemonlight"
author = "robotkoer"
version = "11.3.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f1d2164eb6150117ff5b9b355082b2a900fbdd71b1a2fc1c243910410133471b"

[versions]
fabric = "0.19.3"
minecraft = "1.21.10"
