name = "Lemonlight Full"
author = "robotkoer"
version = "15.0.0-alpha.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c331c5bfbb1d6e8f17d1b4964ea9cf7d607afbcea39d4758c2b3e9747f770600"

[versions]
fabric = "0.19.5"
minecraft = "26.3"
