name = "Lemonlight Full"
author = "robotkoer"
version = "15.0.0-alpha.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f57aa3d12ae155fa599d97cf73af94e4ae9d6fe007ed9c5111778b19c1cc3067"

[versions]
fabric = "0.19.5"
minecraft = "26.3"
