name = "Lemonlight"
author = "robotkoer"
version = "13.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8140d8b23dd42a3a7e46d271532d3e198b6409b337554ea3cbbfd6cc1d21aad1"

[versions]
fabric = "0.19.5"
minecraft = "26.1.2"
