name = "Lemonlight"
author = "robotkoer"
version = "13.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "85a9ab56c43a6bd10afa1ee0207048a6076be888aacd42747179e556d5049a01"

[versions]
fabric = "0.19.5"
minecraft = "26.1.2"
