name = "Lemonlight"
version = "4.1.0-beta.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6736be5d66f148a17f942892f62e8d55778cde9c96c9bb526f384c7adc35c2e8"

[versions]
fabric = "0.14.8"
minecraft = "1.19.1"
