name = "Lemonlight Full"
author = "robotkoer"
version = "14.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "207d505b3ed2e343d80f35ab6b57a06e2a8131fa836d57baf78de98ea6e7d0ab"

[versions]
fabric = "0.19.5"
minecraft = "26.2"
