name = "Lemonlight"
author = "robotkoer"
version = "10.0.0-alpha.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fbe83101694a40393c55e03fa1f85915acc9a41b4f9a17a776c078f43298a08c"

[versions]
fabric = "0.16.14"
minecraft = "1.21.6"
