name = "Lemonlight"
author = "robotkoer"
version = "4.12.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a3b92ff67ae92ecf875bd684b176353adf7926b00e4aebd33ca3dfe40cbad9ef"

[versions]
fabric = "0.19.3"
minecraft = "1.19.4"
