name = "Lemonlight"
author = "robotkoer"
version = "5.11.0-alpha.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "94ea68b375260ce69dbf3127a5814f1c068da46cb9e135a32c60147f2cd397cc"

[versions]
fabric = "0.15.10"
minecraft = "1.20.5"
